apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Content-Type-Options "nosniff";
      add_header X-XSS-Protection "1; mode=block";
      add_header X-Frame-Options "DENY";
      add_header Content-Security-Policy "script-src 'self' *.baidu.com 'unsafe-inline' 'unsafe-eval'; object-src 'none'; frame-src https://cdn.jsdelivr.net xihes-ais.authing.cn *.mindspore.cn";
      add_header Cache-Control "no-cache";
      add_header Pragma "no-cache";
  name: xihe-ingress
  namespace: xihe-new
spec:
  tls:
    - hosts:
        - xihe.mindspore.cn
      secretName: xihe-mindspore-tls
  rules:
    - host: xihe.mindspore.cn
      http:
        paths:
          - backend:
              serviceName: xihe-website-service
              servicePort: 80
            path: /

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: xihe-mindspore-tls
  namespace: xihe-new
spec:
  name: xihe-mindspore-tls
  keysMap:
    ca.crt:
      path: secrets/data/mindspore/xihe
      key: server.crt
    tls.crt:
      path: secrets/data/mindspore/xihe
      key: server.crt
    tls.key:
      path: secrets/data/mindspore/xihe
      key: server.key
