---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xihe-website
  namespace: xihe-test-v2-website
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xihe-website
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-perms-server.crt: "0400"
        vault.hashicorp.com/agent-inject-perms-server.key: "0400"
        vault.hashicorp.com/agent-inject-perms-abc.txt: "0400"
        vault.hashicorp.com/agent-inject-perms-dhparam.pem: "0600"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/nginx/cert/"
        vault.hashicorp.com/agent-inject-secret-server.crt: "internal/data/mindspore/xihe-test-v2-website"
        vault.hashicorp.com/agent-inject-template-server.crt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2-website" -}}
          {{ .Data.data.ServerCrt }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-server.key: "internal/data/mindspore/xihe-test-v2-website"
        vault.hashicorp.com/agent-inject-template-server.key: |
          {{- with secret "internal/data/mindspore/xihe-test-v2-website" -}}
          {{ .Data.data.ServerKey }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-abc.txt: "internal/data/mindspore/xihe-test-v2-website"
        vault.hashicorp.com/agent-inject-template-abc.txt: |
          {{- with secret "internal/data/mindspore/xihe-test-v2-website" -}}
          {{ .Data.data.certificatePassword }}
          {{- end }}
        vault.hashicorp.com/agent-inject-secret-dhparam.pem: "internal/data/mindspore/xihe-test-v2-website"
        vault.hashicorp.com/agent-inject-template-dhparam.pem: |
          {{- with secret "internal/data/mindspore/xihe-test-v2-website" -}}
          {{ .Data.data.dhparamPem }}
          {{- end }}
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: xihe-website
      labels:
        app: xihe-website
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: xihe-website
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: xihe-website
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/xihe/xihe-website-test:2e7c9d92da5c19264286a54ff29381bca4652bf9
        imagePullPolicy: IfNotPresent
        env:
        - name: DET_URL
          value: https://xihe2.test.osinfra.cn
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1000Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
